# Generated by Django 2.2 on 2020-03-28 15:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200328_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.image_folder, verbose_name='Изображение товара'),
        ),
    ]
